   [build]
     # Directory to change to before starting a build
     base = "/"
     
     # Directory that contains the deploy-ready HTML files and assets
     publish = "frontend/"
     
     # Build command
     command = "# No build command needed for this project"

   [functions]
     directory = "backend/"

   [[redirects]]
     from = "/api/*"
     to = "/.netlify/functions/:splat"
     status = 200